version: "2"
services:
  worker01:
    build: ./
    ports:
      - "8081:8080"
    links:
      - mongocontainer
  worker02:
    build: ./
    ports:
      - "8082:8080"
    links:
      - mongocontainer
  worker03:
    build: ./
    ports:
      - "8083:8080"
    links:
      - mongocontainer
  worker04:
    build: ./
    ports:
      - "8084:8080"
    links:
      - mongocontainer
  mongocontainer:
    image: mongo
    ports:
      - "27017:27017"