version: "2"
services:
  master:
    build: ./distributed-master
    ports:
      - "8081:8080"
  worker01:
    build: ./distributed-worker
    ports:
      - "8082:8080"
    links:
      - mongocontainer
      - master
#    entrypoint: ./wait-master.sh master:8081
  worker02:
    build: ./distributed-worker
    ports:
      - "8083:8080"
    links:
      - mongocontainer
      - master
#    entrypoint: ./wait-master.sh master:8081
  worker03:
    build: ./distributed-worker
    ports:
      - "8084:8080"
    links:
      - mongocontainer
      - master
#    entrypoint: ./wait-master.sh master:8081
  worker04:
    build: ./distributed-worker
    ports:
      - "8085:8080"
    links:
      - mongocontainer
      - master
#    entrypoint: ./wait-master.sh master:8081
  mongocontainer:
    image: mongo
    ports:
      - "27017:27017"